# ARM64 Linux 交叉编译配置 - Meson 原生格式
[binaries]
c = 'aarch64-openeuler-linux-gcc'
cpp = 'aarch64-openeuler-linux-g++'
ar = 'aarch64-openeuler-linux-ar'
strip = 'aarch64-openeuler-linux-strip'
pkg-config = 'pkg-config'

[host_machine]
system = 'linux'
cpu_family = 'aarch64'
cpu = 'cortex-a72'
endian = 'little'

[built-in options]
; ['plain', 'debug', 'debugoptimized', 'release', 'minsize']
buildtype = 'debugoptimized'
c_args = ['-fPIC']
cpp_args = ['-fPIC']
c_link_args = ['-Wl,--no-undefined']
cpp_link_args = ['-Wl,--no-undefined']

[properties]
pkg_config_libdir = ['/opt/cross-deps/msf-euler/lib/pkgconfig']
needs_exe_wrapper = true

[project options]
enable_lynxi = true
enable_opencv = true

[lynxi:project options]
lynxi_root = '/opt/cross-deps/msf-euler'