# Linux 本地编译配置 - Meson 原生格式
[binaries]
c = 'clang'
cpp = 'clang++'
ar = 'ar'
strip = 'strip'
pkg-config = 'pkg-config'

[built-in options] 
; ['plain', 'debug', 'debugoptimized', 'release', 'minsize']'/opt/opencv/opencv_x86/lib/pkgconfig'
buildtype = 'debug'
c_args = ['-fPIC']
cpp_args = ['-fPIC']
pkg_config_path = ['/usr/local/lib/pkgconfig']

[properties]

[project options]
spdlog_mode = 'shared'