# Windows 本地编译配置 - Meson 原生格式
[binaries]
c = 'cl.exe'
cpp = 'cl.exe'
ar = 'lib.exe'
; strip = 'strip.exe' msvc 没有

[built-in options]
buildtype = 'debugoptimized'
b_pch = false
c_args = ['/MD']
cpp_args = ['/MD']

[project options]
enable_opencv = true